Database:
    DBtype: postgres
    Username: postgres
    Password: 124411082
    Host: 104.214.48.227
    Part: 5432
    DBName: club
    TablePrefix: club_
    Charset: utf8
    ParseTime: True
    MaxIdleConns: 10
    MaxOpenConns: 30
